## Data pre-processing
Data pre-processing is a critical step in the data science workflow.

It involves preparing and transforming raw data into a suitable format that allows 
for more effective analysis and modeling.

### Why we do Data PreProcessing:

Learning algorithms have affinity towards certain pattern of data.

Unscaled or unstandardized data might have unacceptable prediction

Learning algorithms understands only number, converting text or image to number is required

Preprocessing refers to transformation of data before feeding to machine learning model

In [1]:
# #Checklist or steps to perform a ML/DL problems


# 1)Define/understand the problem statement
# 2)Get the Data -10%
# 3)EDA -Exploratory Data Analysis(Data Visualization)- 10%
# 4)Data Preprocessing(Data Cleaning) - 70%
# 5)Model training -5%
# 6)Select one model and fine tune it(Hyper-parameter tuning)- 5%
# 7)Evaluate the model performance -5%
# 8)Deploy and Monitor the model perf in prod/real time

# PreProcessing using scikit-learn


<img src="https://github.com/awantik/machine-learning-slides/blob/master/ML-Pipeline.png?raw=true">

### Steps In preprocessing:
    
Extract Target Variable: Indexing: loc, iloc, name

Extract Predictor Variable: Indexing: loc, iloc, names,slicing

Finding Missing Data

Encoding Categorical Data

Feature scaling

Splitting dataset into training and test set

#### Common import

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns; sns.set(color_codes=True)
import matplotlib.pyplot as plt
%matplotlib inline

### Given the salary dataset , predict the BasePay

In [4]:
#1) select the target features
df=pd.read_csv("Salaries.csv")
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [5]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [5]:
#selecting input columns...ie all independent features/attributes
X=df.loc[:,df.columns!="BasePay"] # : is select all rows  and df.columns != "BasePay" returns a boolean mask: True for every column name that's not "BasePay"
X.head()

,Id,EmployeeName,JobTitle,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [6]:
y=df.loc[:,"BasePay"] #This line extracts the "BasePay" column from the DataFrame df and assigns it to y, which will be your target variable.
y.head() # shows first 5 values from data set

0    167411.18
1    155966.02
2    212739.13
3     77916.00
4    134401.60
Name: BasePay, dtype: float64

In [7]:
y.shape # contains only one column and num of rows 148654

(148654,)

In [8]:
X.shape # contains 12 columns and 148654 rows

(148654, 12)

### 1.Select your Target feature

In [9]:
df=pd.read_csv("Salaries.csv")
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [10]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [11]:
# X=df.loc[:, df.columns != 'BasePay']

X=df.iloc[:,[0,1,2,4,5,6,8,9]]
# loc[rows,cols] - logic

In [12]:
X.head()

,Id,EmployeeName,JobTitle,OvertimePay,OtherPay,Benefits,TotalPayBenefits,Year
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,0.00,400184.25,NaN,567595.43,2011
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),245131.88,137811.38,NaN,538909.28,2011
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),106088.18,16452.60,NaN,335279.91,2011
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,56120.71,198306.90,NaN,332343.61,2011
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",9737.00,182234.59,NaN,326373.19,2011

In [13]:
y=df.iloc[:,[3]]

In [14]:
y.head()

     BasePay
0  167411.18
1  155966.02
2  212739.13
3   77916.00
4  134401.60

In [15]:
#2nd  approach of selecting X and y

X=df.drop(["BasePay"],axis=1) #axis=1 → drop columns axis=0 → drop rows
# "BasePay" is a column, so use axis=1
X.head()

,Id,EmployeeName,JobTitle,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [16]:
y=df["BasePay"]
y

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...
148649         0.00
148650          NaN
148651          NaN
148652          NaN
148653         0.00
Name: BasePay, Length: 148654, dtype: float64

In [17]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [18]:
df.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')

In [19]:
#3rd approach,slicing or selecting column based on list of column names
col_names=['Id', 'EmployeeName', 'JobTitle', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status']
X=df[col_names]
X.head()

,Id,EmployeeName,JobTitle,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [20]:
y=df["BasePay"]
y.head()

0    167411.18
1    155966.02
2    212739.13
3     77916.00
4    134401.60
Name: BasePay, dtype: float64

In [21]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [22]:
df.shape

(148654, 13)

In [23]:
X.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'OvertimePay', 'OtherPay', 'Benefits',
       'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency', 'Status'],
      dtype='object')

In [24]:
X.head()

,Id,EmployeeName,JobTitle,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [25]:
y.head()

0    167411.18
1    155966.02
2    212739.13
3     77916.00
4    134401.60
Name: BasePay, dtype: float64

In [26]:
X.shape

(148654, 12)

In [6]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\ghane\anaconda3\lib\site-packages (1.6.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.19.5 in c:\users\ghane\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\ghane\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ghane\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ghane\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [7]:
#Train test split
# pip install scikit-learn
from sklearn.model_selection import train_test_split
#  This imports the train_test_split function from scikit-learn, which is used to randomly split your dataset into training and testing sets.


X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.80)

# X → your feature matrix (independent variables)

# y → your target variable ("BasePay")

# The function splits them into:

# X_train: 80% of X for training

# X_test: 20% of X for testing

# y_train: 80% of y corresponding to X_train

# y_test: 20% of y corresponding to X_test

X_train.shape

NameError: name 'X' is not defined

In [106]:
y_train.shape

(118923,)

In [29]:
X_test.shape

(29731, 12)

In [107]:
y_test.shape

(29731,)

In [30]:
X_train.head()

,Id,EmployeeName,JobTitle,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
146498,146499,Donald R Maffei,Conversion,0.00,3361.44,0.00,3361.44,3361.44,2014,NaN,San Francisco,NaN
60067,60068,Ramon Jayme,Bldg & Grounds Patrol Officer,84.13,2169.35,26640.47,54631.56,81272.03,2012,NaN,San Francisco,NaN
89631,89632,Michael R Duckworth,Automotive Machinist,0.00,1290.03,29214.01,79680.84,108894.85,2013,NaN,San Francisco,NaN
22228,22229,DAVID VIDRIO,ASSISTANT RECREATION DIRECTOR,0.00,29945.25,NaN,57033.10,57033.10,2011,NaN,San Francisco,NaN
6172,6173,MICHAEL BUSHNELL,POLICE OFFICER I,9261.54,11838.70,NaN,117804.57,117804.57,2011,NaN,San Francisco,NaN

In [31]:
y_train.head()

146498        0.00
60067     52378.08
89631     78390.81
22228     27087.85
6172      96704.33
Name: BasePay, dtype: float64

In [34]:
X_test.head()

,Id,EmployeeName,JobTitle,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
142593,142594,Tegwyn L Lewis-Pine,Special Nurse,0.00,215.11,156.11,15610.73,15766.84,2014,NaN,San Francisco,NaN
12910,12911,MANUEL SAN JUAN,WATER QUALITY TECHNICIAN I/II,11289.35,0.00,NaN,85179.44,85179.44,2011,NaN,San Francisco,NaN
142546,142547,Perry Clark,Automotive Service Worker,0.00,4324.07,3732.80,12262.03,15994.83,2014,NaN,San Francisco,NaN
15486,15487,VENNIE PAYNE,TRANSIT OPERATOR,10414.48,1414.62,NaN,75967.51,75967.51,2011,NaN,San Francisco,NaN
32788,32789,JOHN LEE,TRANSIT OPERATOR,0.00,2515.99,NaN,6530.71,6530.71,2011,NaN,San Francisco,NaN

In [37]:
y_test.head()

142593    15395.62
12910     73890.09
142546     7937.96
15486     64138.41
32788      4014.72
Name: BasePay, dtype: float64

## Handling Missing Data:



Why missing data is a concern?

Missing data can create major risk of producing incorrect conclusions due to absence of relevant information leading to invalid results.

Results of any statistical analysis used can be only as good as the quality of the data.

missing data arises for many reasons such as non-response, lost data, or skip patterns in surveys.

Let us familiarize what are the most common types of missing data.

1. Delete the row
2. Impute a mean/median value 
3. Drop feature if missing value is extremely high

In [48]:
df=pd.read_csv("Salaries.csv")
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [49]:
df.shape

(148654, 13)

In [50]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [51]:
df.isnull().sum().sum()

334088

In [52]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [53]:
missing_per=df.isnull().sum()/len(df) * 100
missing_per

Id                    0.000000
EmployeeName          0.000000
JobTitle              0.000000
BasePay               0.409676
OvertimePay           0.002691
OtherPay              0.002691
Benefits             24.326961
TotalPay              0.000000
TotalPayBenefits      0.000000
Year                  0.000000
Notes               100.000000
Agency                0.000000
Status              100.000000
dtype: float64

In [1]:
import numpy as np
import pandas as pd     
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
  
# creating a dataframe from dictionary
xyz = pd.DataFrame(dict)
xyz.head()

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [3]:
#backfill  and forwardfill
xyz.fillna(method ='ffill')

C:\Users\USER\AppData\Local\Temp\ipykernel_1180\1627756806.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  xyz.fillna(method ='ffill')

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [56]:

import numpy as np
import pandas as pd     
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
  
# creating a dataframe from dictionary
abc= pd.DataFrame(dict)
# abc.head()


a=abc.replace(to_replace = np.nan, value = -99) 
a.head()

   First Score  Second Score  Third Score
0        100.0          30.0        -99.0
1         90.0          45.0         40.0
2        -99.0          56.0         80.0
3         95.0         -99.0         98.0

In [57]:
import numpy as np
import pandas as pd     
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
  
# creating a dataframe from dictionary
pqr= pd.DataFrame(dict)
pqr.head()

pqr.dropna(how="any")

   First Score  Second Score  Third Score
1         90.0          45.0         40.0

In [58]:
# df.fillna(method ='bfill') # dont do this

In [59]:
df["OvertimePay"]=df["OvertimePay"].fillna(method="bfill")

C:\Users\USER\AppData\Local\Temp\ipykernel_9892\1158335177.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["OvertimePay"]=df["OvertimePay"].fillna(method="bfill")

In [60]:
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              0
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [61]:
df.iloc[0]

Id                                                               1
EmployeeName                                        NATHANIEL FORD
JobTitle            GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
BasePay                                                  167411.18
OvertimePay                                                    0.0
OtherPay                                                 400184.25
Benefits                                                       NaN
TotalPay                                                 567595.43
TotalPayBenefits                                         567595.43
Year                                                          2011
Notes                                                          NaN
Agency                                               San Francisco
Status                                                         NaN
Name: 0, dtype: object

In [62]:
#dont do this in industry/company
for i in range(len(df.index)):
    print(f"Missing value in row {i} = {df.iloc[i].isnull().sum()}")

Missing value in row 0 = 3
Missing value in row 1 = 3
Missing value in row 2 = 3
Missing value in row 3 = 3
Missing value in row 4 = 3
Missing value in row 5 = 3
Missing value in row 6 = 3
Missing value in row 7 = 3
Missing value in row 8 = 3
Missing value in row 9 = 3
Missing value in row 10 = 3
Missing value in row 11 = 3
Missing value in row 12 = 3
Missing value in row 13 = 3
Missing value in row 14 = 3
Missing value in row 15 = 3
Missing value in row 16 = 3
Missing value in row 17 = 3
Missing value in row 18 = 3
Missing value in row 19 = 3
Missing value in row 20 = 3
Missing value in row 21 = 3
Missing value in row 22 = 3
Missing value in row 23 = 3
Missing value in row 24 = 3
Missing value in row 25 = 3
Missing value in row 26 = 3
Missing value in row 27 = 3
Missing value in row 28 = 3
Missing value in row 29 = 3
Missing value in row 30 = 3
Missing value in row 31 = 3
Missing value in row 32 = 3
Missing value in row 33 = 3
Missing value in row 34 = 3
Missing value in row 35 = 3
Missing value in row 36 = 3
Missing value in row 37 = 3
Missing value in row 38 = 3
Missing value in row 39 = 3
Missing value in row 40 = 3
Missing value in row 41 = 3
Missing value in row 42 = 3
Missing value in row 43 = 3
Missing value in row 44 = 3
Missing value in row 45 = 3
Missing value in row 46 = 3
Missing value in row 47 = 3
Missing value in row 48 = 3
Missing value in row 49 = 3
Missing value in row 50 = 3
Missing value in row 51 = 3
Missing value in row 52 = 3
Missing value in row 53 = 3
Missing value in row 54 = 3
Missing value in row 55 = 3
Missing value in row 56 = 3
Missing value in row 57 = 3
Missing value in row 58 = 3
Missing value in row 59 = 3
Missing value in row 60 = 3
Missing value in row 61 = 3
Missing value in row 62 = 3
Missing value in row 63 = 3
Missing value in row 64 = 3
Missing value in row 65 = 3
Missing value in row 66 = 3
Missing value in row 67 = 3
Missing value in row 68 = 3
Missing value in row 69 = 3
Missing value in row 70 = 3
Missing value in row 71 = 3
Missing value in row 72 = 3
Missing value in row 73 = 3
Missing value in row 74 = 3
Missing value in row 75 = 3
Missing value in row 76 = 3
Missing value in row 77 = 3
Missing value in row 78 = 3
Missing value in row 79 = 3
Missing value in row 80 = 3
Missing value in row 81 = 3
Missing value in row 82 = 3
Missing value in row 83 = 3
Missing value in row 84 = 3
Missing value in row 85 = 3
Missing value in row 86 = 3
Missing value in row 87 = 3
Missing value in row 88 = 3
Missing value in row 89 = 3
Missing value in row 90 = 3
Missing value in row 91 = 3
Missing value in row 92 = 3
Missing value in row 93 = 3
Missing value in row 94 = 3
Missing value in row 95 = 3
Missing value in row 96 = 3
Missing value in row 97 = 3
Missing value in row 98 = 3
Missing value in row 99 = 3
Missing value in row 100 = 3
Missing value in row 101 = 3
Missing value in row 102 = 3
Missing value in row 103 = 3
Missing value in row 104 = 3
Missing value in row 105 = 3
Missing value in row 106 = 3
Missing value in row 107 = 3
Missing value in row 108 = 3
Missing value in row 109 = 3
Missing value in row 110 = 3
Missing value in row 111 = 3
Missing value in row 112 = 3
Missing value in row 113 = 3
Missing value in row 114 = 3
Missing value in row 115 = 3
Missing value in row 116 = 3
Missing value in row 117 = 3
Missing value in row 118 = 3
Missing value in row 119 = 3
Missing value in row 120 = 3
Missing value in row 121 = 3
Missing value in row 122 = 3
Missing value in row 123 = 3
Missing value in row 124 = 3
Missing value in row 125 = 3
Missing value in row 126 = 3
Missing value in row 127 = 3
Missing value in row 128 = 3
Missing value in row 129 = 3
Missing value in row 130 = 3
Missing value in row 131 = 3
Missing value in row 132 = 3
Missing value in row 133 = 3
Missing value in row 134 = 3
Missing value in row 135 = 3
Missing value in row 136 = 3
Missing value in row 137 = 3
Missing value in row 138 = 3
Missing value in row 139 = 3
Missing value in row 140 = 3
Missing value in row 141 = 3
Missing value in row 142 = 3
Missing value in row 143 = 3
Missing value in row 144 = 3
Missing value in row 145 = 3
Missing value in row 146 = 3
Missing value in row 147 = 3
Missing value in row 148 = 3
Missing value in row 149 = 3
Missing value in row 150 = 3
Missing value in row 151 = 3
Missing value in row 152 = 3
Missing value in row 153 = 3
Missing value in row 154 = 3
Missing value in row 155 = 3
Missing value in row 156 = 3
Missing value in row 157 = 3
Missing value in row 158 = 3
Missing value in row 159 = 3
Missing value in row 160 = 3
Missing value in row 161 = 3
Missing value in row 162 = 3
Missing value in row 163 = 3
Missing value in row 164 = 3
Missing value in row 165 = 3
Missing value in row 166 = 3
Missing value in row 167 = 3
Missing value in row 168 = 3
Missing value in row 169 = 3
Missing value in row 170 = 3
Missing value in row 171 = 3
Missing value in row 172 = 3
Missing value in row 173 = 3
Missing value in row 174 = 3
Missing value in row 175 = 3
Missing value in row 176 = 3
Missing value in row 177 = 3
Missing value in row 178 = 3
Missing value in row 179 = 3
Missing value in row 180 = 3
Missing value in row 181 = 3
Missing value in row 182 = 3
Missing value in row 183 = 3
Missing value in row 184 = 3
Missing value in row 185 = 3
Missing value in row 186 = 3
Missing value in row 187 = 3
Missing value in row 188 = 3
Missing value in row 189 = 3
Missing value in row 190 = 3
Missing value in row 191 = 3
Missing value in row 192 = 3
Missing value in row 193 = 3
Missing value in row 194 = 3
Missing value in row 195 = 3
Missing value in row 196 = 3
Missing value in row 197 = 3
Missing value in row 198 = 3
Missing value in row 199 = 3
Missing value in row 200 = 3
Missing value in row 201 = 3
Missing value in row 202 = 3
Missing value in row 203 = 3
Missing value in row 204 = 3
Missing value in row 205 = 3
Missing value in row 206 = 3
Missing value in row 207 = 3
Missing value in row 208 = 3
Missing value in row 209 = 3
Missing value in row 210 = 3
Missing value in row 211 = 3
Missing value in row 212 = 3
Missing value in row 213 = 3
Missing value in row 214 = 3
Missing value in row 215 = 3
Missing value in row 216 = 3
Missing value in row 217 = 3
Missing value in row 218 = 3
Missing value in row 219 = 3
Missing value in row 220 = 3
Missing value in row 221 = 3
Missing value in row 222 = 3
Missing value in row 223 = 3
Missing value in row 224 = 3
Missing value in row 225 = 3
Missing value in row 226 = 3
Missing value in row 227 = 3
Missing value in row 228 = 3
Missing value in row 229 = 3
Missing value in row 230 = 3
Missing value in row 231 = 3
Missing value in row 232 = 3
Missing value in row 233 = 3
Missing value in row 234 = 3
Missing value in row 235 = 3
Missing value in row 236 = 3
Missing value in row 237 = 3
Missing value in row 238 = 3
Missing value in row 239 = 3
Missing value in row 240 = 3
Missing value in row 241 = 3
Missing value in row 242 = 3
Missing value in row 243 = 3
Missing value in row 244 = 3
Missing value in row 245 = 3
Missing value in row 246 = 3
Missing value in row 247 = 3
Missing value in row 248 = 3
Missing value in row 249 = 3
Missing value in row 250 = 3
Missing value in row 251 = 3
Missing value in row 252 = 3
Missing value in row 253 = 3
Missing value in row 254 = 3
Missing value in row 255 = 3
Missing value in row 256 = 3
Missing value in row 257 = 3
Missing value in row 258 = 3
Missing value in row 259 = 3
Missing value in row 260 = 3
Missing value in row 261 = 3
Missing value in row 262 = 3
Missing value in row 263 = 3
Missing value in row 264 = 3
Missing value in row 265 = 3
Missing value in row 266 = 3
Missing value in row 267 = 3
Missing value in row 268 = 3
Missing value in row 269 = 3
Missing value in row 270 = 3
Missing value in row 271 = 3
Missing value in row 272 = 3
Missing value in row 273 = 3
Missing value in row 274 = 3
Missing value in row 275 = 3
Missing value in row 276 = 3
Missing value in row 277 = 3
Missing value in row 278 = 3
Missing value in row 279 = 3
Missing value in row 280 = 3
Missing value in row 281 = 3
Missing value in row 282 = 3
Missing value in row 283 = 3
Missing value in row 284 = 3
Missing value in row 285 = 3
Missing value in row 286 = 3
Missing value in row 287 = 3
Missing value in row 288 = 3
Missing value in row 289 = 3
Missing value in row 290 = 3
Missing value in row 291 = 3
Missing value in row 292 = 3
Missing value in row 293 = 3
Missing value in row 294 = 3
Missing value in row 295 = 3
Missing value in row 296 = 3
Missing value in row 297 = 3
Missing value in row 298 = 3
Missing value in row 299 = 3
Missing value in row 300 = 3
Missing value in row 301 = 3
Missing value in row 302 = 3
Missing value in row 303 = 3
Missing value in row 304 = 3
Missing value in row 305 = 3
Missing value in row 306 = 3
Missing value in row 307 = 3
Missing value in row 308 = 3
Missing value in row 309 = 3
Missing value in row 310 = 3
Missing value in row 311 = 3
Missing value in row 312 = 3
Missing value in row 313 = 3
Missing value in row 314 = 3
Missing value in row 315 = 3
Missing value in row 316 = 3
Missing value in row 317 = 3
Missing value in row 318 = 3
Missing value in row 319 = 3
Missing value in row 320 = 3
Missing value in row 321 = 3
Missing value in row 322 = 3
Missing value in row 323 = 3
Missing value in row 324 = 3
Missing value in row 325 = 3
Missing value in row 326 = 3
Missing value in row 327 = 3
Missing value in row 328 = 3
Missing value in row 329 = 3
Missing value in row 330 = 3
Missing value in row 331 = 3
Missing value in row 332 = 3
Missing value in row 333 = 3
Missing value in row 334 = 3
Missing value in row 335 = 3
Missing value in row 336 = 3
Missing value in row 337 = 3
Missing value in row 338 = 3
Missing value in row 339 = 3
Missing value in row 340 = 3
Missing value in row 341 = 3
Missing value in row 342 = 3
Missing value in row 343 = 3
Missing value in row 344 = 3
Missing value in row 345 = 3
Missing value in row 346 = 3
Missing value in row 347 = 3
Missing value in row 348 = 3
Missing value in row 349 = 3
Missing value in row 350 = 3
Missing value in row 351 = 3
Missing value in row 352 = 3
Missing value in row 353 = 3
Missing value in row 354 = 3
Missing value in row 355 = 3
Missing value in row 356 = 3
Missing value in row 357 = 3
Missing value in row 358 = 3
Missing value in row 359 = 3
Missing value in row 360 = 3
Missing value in row 361 = 3
Missing value in row 362 = 3
Missing value in row 363 = 3
Missing value in row 364 = 3
Missing value in row 365 = 3
Missing value in row 366 = 3
Missing value in row 367 = 3
Missing value in row 368 = 3
Missing value in row 369 = 3
Missing value in row 370 = 3
Missing value in row 371 = 3
Missing value in row 372 = 3
Missing value in row 373 = 3
Missing value in row 374 = 3
Missing value in row 375 = 3
Missing value in row 376 = 3
Missing value in row 377 = 3
Missing value in row 378 = 3
Missing value in row 379 = 3
Missing value in row 380 = 3
Missing value in row 381 = 3
Missing value in row 382 = 3
Missing value in row 383 = 3
Missing value in row 384 = 3
Missing value in row 385 = 3
Missing value in row 386 = 3
Missing value in row 387 = 3
Missing value in row 388 = 3
Missing value in row 389 = 3
Missing value in row 390 = 3
Missing value in row 391 = 3
Missing value in row 392 = 3
Missing value in row 393 = 3
Missing value in row 394 = 3
Missing value in row 395 = 3
Missing value in row 396 = 3
Missing value in row 397 = 3
Missing value in row 398 = 3
Missing value in row 399 = 3
Missing value in row 400 = 3
Missing value in row 401 = 3
Missing value in row 402 = 3
Missing value in row 403 = 3
Missing value in row 404 = 3
Missing value in row 405 = 3
Missing value in row 406 = 3
Missing value in row 407 = 3
Missing value in row 408 = 3
Missing value in row 409 = 3
Missing value in row 410 = 3
Missing value in row 411 = 3
Missing value in row 412 = 3
Missing value in row 413 = 3
Missing value in row 414 = 3
Missing value in row 415 = 3
Missing value in row 416 = 3
Missing value in row 417 = 3
Missing value in row 418 = 3
Missing value in row 419 = 3
Missing value in row 420 = 3
Missing value in row 421 = 3
Missing value in row 422 = 3
Missing value in row 423 = 3
Missing value in row 424 = 3
Missing value in row 425 = 3
Missing value in row 426 = 3
Missing value in row 427 = 3
Missing value in row 428 = 3
Missing value in row 429 = 3
Missing value in row 430 = 3
Missing value in row 431 = 3
Missing value in row 432 = 3
Missing value in row 433 = 3
Missing value in row 434 = 3
Missing value in row 435 = 3
Missing value in row 436 = 3
Missing value in row 437 = 3
Missing value in row 438 = 3
Missing value in row 439 = 3
Missing value in row 440 = 3
Missing value in row 441 = 3
Missing value in row 442 = 3
Missing value in row 443 = 3
Missing value in row 444 = 3
Missing value in row 445 = 3
Missing value in row 446 = 3
Missing value in row 447 = 3
Missing value in row 448 = 3
Missing value in row 449 = 3
Missing value in row 450 = 3
Missing value in row 451 = 3
Missing value in row 452 = 3
Missing value in row 453 = 3
Missing value in row 454 = 3
Missing value in row 455 = 3
Missing value in row 456 = 3
Missing value in row 457 = 3
Missing value in row 458 = 3
Missing value in row 459 = 3
Missing value in row 460 = 3
Missing value in row 461 = 3
Missing value in row 462 = 3
Missing value in row 463 = 3
Missing value in row 464 = 3
Missing value in row 465 = 3
Missing value in row 466 = 3
Missing value in row 467 = 3
Missing value in row 468 = 3
Missing value in row 469 = 3
Missing value in row 470 = 3
Missing value in row 471 = 3
Missing value in row 472 = 3
Missing value in row 473 = 3
Missing value in row 474 = 3
Missing value in row 475 = 3
Missing value in row 476 = 3
Missing value in row 477 = 3
Missing value in row 478 = 3
Missing value in row 479 = 3
Missing value in row 480 = 3
Missing value in row 481 = 3
Missing value in row 482 = 3
Missing value in row 483 = 3
Missing value in row 484 = 3
Missing value in row 485 = 3
Missing value in row 486 = 3
Missing value in row 487 = 3
Missing value in row 488 = 3
Missing value in row 489 = 3
Missing value in row 490 = 3
Missing value in row 491 = 3
Missing value in row 492 = 3
Missing value in row 493 = 3
Missing value in row 494 = 3
Missing value in row 495 = 3
Missing value in row 496 = 3
Missing value in row 497 = 3
Missing value in row 498 = 3
Missing value in row 499 = 3
Missing value in row 500 = 3
Missing value in row 501 = 3
Missing value in row 502 = 3
Missing value in row 503 = 3
Missing value in row 504 = 3
Missing value in row 505 = 3
Missing value in row 506 = 3
Missing value in row 507 = 3
Missing value in row 508 = 3
Missing value in row 509 = 3
Missing value in row 510 = 3
Missing value in row 511 = 3
Missing value in row 512 = 3
Missing value in row 513 = 3
Missing value in row 514 = 3
Missing value in row 515 = 3
Missing value in row 516 = 3
Missing value in row 517 = 3
Missing value in row 518 = 3
Missing value in row 519 = 3
Missing value in row 520 = 3
Missing value in row 521 = 3
Missing value in row 522 = 3
Missing value in row 523 = 3
Missing value in row 524 = 3
Missing value in row 525 = 3
Missing value in row 526 = 3
Missing value in row 527 = 3
Missing value in row 528 = 3
Missing value in row 529 = 3
Missing value in row 530 = 3
Missing value in row 531 = 3
Missing value in row 532 = 3
Missing value in row 533 = 3
Missing value in row 534 = 3
Missing value in row 535 = 3
Missing value in row 536 = 3
Missing value in row 537 = 3
Missing value in row 538 = 3
Missing value in row 539 = 3
Missing value in row 540 = 3
Missing value in row 541 = 3
Missing value in row 542 = 3
Missing value in row 543 = 3
Missing value in row 544 = 3
Missing value in row 545 = 3
Missing value in row 546 = 3
Missing value in row 547 = 3
Missing value in row 548 = 3
Missing value in row 549 = 3
Missing value in row 550 = 3
Missing value in row 551 = 3
Missing value in row 552 = 3
Missing value in row 553 = 3
Missing value in row 554 = 3
Missing value in row 555 = 3
Missing value in row 556 = 3
Missing value in row 557 = 3
Missing value in row 558 = 3
Missing value in row 559 = 3
Missing value in row 560 = 3
Missing value in row 561 = 3
Missing value in row 562 = 3
Missing value in row 563 = 3
Missing value in row 564 = 3
Missing value in row 565 = 3
Missing value in row 566 = 3
Missing value in row 567 = 3
Missing value in row 568 = 3
Missing value in row 569 = 3
Missing value in row 570 = 3
Missing value in row 571 = 3
Missing value in row 572 = 3
Missing value in row 573 = 3
Missing value in row 574 = 3
Missing value in row 575 = 3
Missing value in row 576 = 3
Missing value in row 577 = 3
Missing value in row 578 = 3
Missing value in row 579 = 3
Missing value in row 580 = 3
Missing value in row 581 = 3
Missing value in row 582 = 3
Missing value in row 583 = 3
Missing value in row 584 = 3
Missing value in row 585 = 3
Missing value in row 586 = 3
Missing value in row 587 = 3
Missing value in row 588 = 3
Missing value in row 589 = 3
Missing value in row 590 = 3
Missing value in row 591 = 3
Missing value in row 592 = 3
Missing value in row 593 = 3
Missing value in row 594 = 3
Missing value in row 595 = 3
Missing value in row 596 = 3
Missing value in row 597 = 3
Missing value in row 598 = 3
Missing value in row 599 = 3
Missing value in row 600 = 3
Missing value in row 601 = 3
Missing value in row 602 = 3
Missing value in row 603 = 3
Missing value in row 604 = 3
Missing value in row 605 = 3
Missing value in row 606 = 3
Missing value in row 607 = 3
Missing value in row 608 = 3
Missing value in row 609 = 3
Missing value in row 610 = 3
Missing value in row 611 = 3
Missing value in row 612 = 3
Missing value in row 613 = 3
Missing value in row 614 = 3
Missing value in row 615 = 3
Missing value in row 616 = 3
Missing value in row 617 = 3
Missing value in row 618 = 3
Missing value in row 619 = 3
Missing value in row 620 = 3
Missing value in row 621 = 3
Missing value in row 622 = 3
Missing value in row 623 = 3
Missing value in row 624 = 3
Missing value in row 625 = 3
Missing value in row 626 = 3
Missing value in row 627 = 3
Missing value in row 628 = 3
Missing value in row 629 = 3
Missing value in row 630 = 3
Missing value in row 631 = 3
Missing value in row 632 = 3
Missing value in row 633 = 3
Missing value in row 634 = 3
Missing value in row 635 = 3
Missing value in row 636 = 3
Missing value in row 637 = 3
Missing value in row 638 = 3
Missing value in row 639 = 3
Missing value in row 640 = 3
Missing value in row 641 = 3
Missing value in row 642 = 3
Missing value in row 643 = 3
Missing value in row 644 = 3
Missing value in row 645 = 3
Missing value in row 646 = 3
Missing value in row 647 = 3
Missing value in row 648 = 3
Missing value in row 649 = 3
Missing value in row 650 = 3
Missing value in row 651 = 3
Missing value in row 652 = 3
Missing value in row 653 = 3
Missing value in row 654 = 3
Missing value in row 655 = 3
Missing value in row 656 = 3
Missing value in row 657 = 3
Missing value in row 658 = 3
Missing value in row 659 = 3
Missing value in row 660 = 3
Missing value in row 661 = 3
Missing value in row 662 = 3
Missing value in row 663 = 3
Missing value in row 664 = 3
Missing value in row 665 = 3
Missing value in row 666 = 3
Missing value in row 667 = 3
Missing value in row 668 = 3
Missing value in row 669 = 3
Missing value in row 670 = 3
Missing value in row 671 = 3
Missing value in row 672 = 3
Missing value in row 673 = 3
Missing value in row 674 = 3
Missing value in row 675 = 3
Missing value in row 676 = 3
Missing value in row 677 = 3
Missing value in row 678 = 3
Missing value in row 679 = 3
Missing value in row 680 = 3
Missing value in row 681 = 3
Missing value in row 682 = 3
Missing value in row 683 = 3
Missing value in row 684 = 3
Missing value in row 685 = 3
Missing value in row 686 = 3
Missing value in row 687 = 3
Missing value in row 688 = 3
Missing value in row 689 = 3
Missing value in row 690 = 3
Missing value in row 691 = 3
Missing value in row 692 = 3

In [63]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [64]:
# df=df.fillna(1) #NEVER EVER do this...

# df.isnull().sum()

In [65]:
df.isnull().mean() *100

Id                    0.000000
EmployeeName          0.000000
JobTitle              0.000000
BasePay               0.409676
OvertimePay           0.000000
OtherPay              0.002691
Benefits             24.326961
TotalPay              0.000000
TotalPayBenefits      0.000000
Year                  0.000000
Notes               100.000000
Agency                0.000000
Status              100.000000
dtype: float64

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148654 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [67]:
df["BasePay"].median()

65007.45

In [68]:
df["BasePay"]=df["BasePay"].fillna(df["BasePay"].median())

In [69]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

In [70]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [71]:
df["JobTitle"].value_counts()

JobTitle
Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ...
CHIEF HOUSING INSPECTOR                              1
TRAFFIC SIGNAL OPERATOR                              1
COURT COMPUTER FACILITIES COORDINATOR                1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
VICTIM & WITNESS TECHNICIAN                          1
Name: count, Length: 2159, dtype: int64

In [72]:
import pandas as pd
import numpy as np

data = {'Category': ['A', 'B', 'A', np.nan, 'B', 'C', 'A', 'C', 'C',"C", np.nan]}
df1 = pd.DataFrame(data)
print("Original DataFrame:")
print(df1)

Original DataFrame:
   Category
0         A
1         B
2         A
3       NaN
4         B
5         C
6         A
7         C
8         C
9         C
10      NaN

In [73]:
v=df1["Category"].mode()
v

0    C
Name: Category, dtype: object

In [74]:
type(v)

pandas.core.series.Series

In [75]:
v[0]

'C'

In [76]:
df1["Category"]=df1["Category"].fillna(df1["Category"].mode()[0])
df1

   Category
0         A
1         B
2         A
3         C
4         B
5         C
6         A
7         C
8         C
9         C
10        C

## 2. StandardScaler
* The StandardScaler assumes your data is normally distributed within each feature and will scale them such that the distribution is now centred around 0, with a standard deviation of 1.
* Calculate - Subtract mean of column & div by standard deviation



<img src="https://github.com/awantik/machine-learning-slides/blob/master/pp4.PNG?raw=true">


* If data is  normally distributed, this is not the best scaler to use.

What is Standardization?
Standardization transforms your features (columns of data) so they have:

a mean (average) of 0

a standard deviation of 1

This is useful when your features have different units/scales, and you want them to be on the same scale.

In [77]:
# example of a standardization
from numpy import asarray
from sklearn.preprocessing import StandardScaler

# define data
data = asarray(
[[100, 0.001],
[8, 0.05],
[50, 0.005],
[88, 0.07],
[4, 0.1]])
# First column: large values (4 to 100)

# Second column: small values (0.001 to 0.1)

# define standard scaler
scaler = StandardScaler()
# transform data
scaled = scaler.fit_transform(data)
print(scaled)

# Interpretation of z-values (standardized values):
# 0 → Value is exactly the mean

# > 0 → Value is above average

# < 0 → Value is below average

#  Why use StandardScaler?
# Many ML algorithms (like Logistic Regression, SVM, KNN) perform better when features are on the same scale.

# It helps with model convergence and avoids biasing the model toward features with larger values.

[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]

## 3. MinMaxScaler
* One of the most popular
* Calculate - Subtract min of column & div by difference between max & min




<img src="https://github.com/awantik/machine-learning-slides/blob/master/pp3.PNG?raw=true">



* Data shifts between 0 & 1
* If distribution not suitable for StandardScaler, this scaler works out.
* Sensitive to outliers

In [78]:

# example of a normalization
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
# define data
data = asarray([
[100, 0.001],
[8, 0.05],
[50, 0.005],
[88, 0.07],
[4, 0.1]])
# define min max scaler
scaler = MinMaxScaler()
# transform data
scaled = scaler.fit_transform(data)
print(scaled)

#  When to use MinMaxScaler?
# Use it when:

# You want to bring all features to a uniform scale

# Your data doesn’t follow a normal distribution

# You're using algorithms sensitive to feature scales (like KNN, SVM, or Neural Networks)

[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.6969697 ]
 [0.         1.        ]]

In [79]:
df=pd.DataFrame(scaled,columns=["Marks","percentage"])
df.head()

      Marks  percentage
0  1.000000    0.000000
1  0.041667    0.494949
2  0.479167    0.040404
3  0.875000    0.696970
4  0.000000    1.000000

In [80]:
type(scaled)

numpy.ndarray

## 4. Encoding Categorical Values 
#### Encoding Ordinal Values
* Ordinal Values - Low, Medium & High. Relationship between values
* LabelEncoding with right mapping

In [81]:
df = pd.DataFrame({
    'Age':[33,44,22,44,55,22],
    'Income':['Low','Low','High','Medium','Medium','High']})

In [82]:
df

   Age  Income
0   33     Low
1   44     Low
2   22    High
3   44  Medium
4   55  Medium
5   22    High

In [83]:
df.Income.unique()

array(['Low', 'High', 'Medium'], dtype=object)

In [84]:
df=df.Income.map({'Low':1,'Medium':2,'High':3})
df.head(10)

0    1
1    1
2    3
3    2
4    2
5    3
Name: Income, dtype: int64

#### PS: We can use transformer class for this as well, we will see that later

#### Encoding Nominal Values
* Nominal Values - Male, Female. No relationship between data
* One Hot Encoding for converting data into one-hot vector

In [85]:
df = pd.DataFrame({
    'Age':[33,44,22,44,55,22,35],
    'Gender':['Male','Female','Male','Female','Male','Male','LGBTQ']})

# Gender is nominal: no inherent order or ranking between the values like Male, Female, LGBTQ.

# You can't directly feed these into most ML models — they need numerical representation.

In [86]:
df.Gender.unique()

array(['Male', 'Female', 'LGBTQ'], dtype=object)

In [87]:
df.head(20)

   Age  Gender
0   33    Male
1   44  Female
2   22    Male
3   44  Female
4   55    Male
5   22    Male
6   35   LGBTQ

In [88]:
df=pd.get_dummies(df, columns=['Gender'],dtype=int)
df.head()

   Age  Gender_Female  Gender_LGBTQ  Gender_Male
0   33              0             0            1
1   44              1             0            0
2   22              0             0            1
3   44              1             0            0
4   55              0             0            1

This drops one column to avoid multicollinearity in regression-based models.

So you'll only see Gender_Female and Gender_LGBTQ.
If both are 0, the row must be Male.

In [89]:
df = pd.DataFrame({
    'Age':[33,44,22,44,55,22,35],
    'Gender':['Male','Female','Male','Female','Male','Male','LGBTQ']})
pd.get_dummies(df, columns=['Gender'],drop_first=True,dtype=int)

   Age  Gender_LGBTQ  Gender_Male
0   33             0            1
1   44             0            0
2   22             0            1
3   44             0            0
4   55             0            1
5   22             0            1
6   35             1            0

In [90]:
df.head()

   Age  Gender
0   33    Male
1   44  Female
2   22    Male
3   44  Female
4   55    Male

In [91]:
df1=pd.get_dummies(df.Gender,dtype=int)

In [92]:
df1.head()

   Female  LGBTQ  Male
0       0      0     1
1       1      0     0
2       0      0     1
3       1      0     0
4       0      0     1

In [93]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [94]:
df.head()

   Age  Gender
0   33    Male
1   44  Female
2   22    Male
3   44  Female
4   55    Male

In [95]:
df["Gender"].value_counts()

Gender
Male      4
Female    2
LGBTQ     1
Name: count, dtype: int64

In [96]:
le = LabelEncoder()
df['gender_tf'] = le.fit_transform(df["Gender"])

In [97]:
df.head(20)

   Age  Gender  gender_tf
0   33    Male          2
1   44  Female          0
2   22    Male          2
3   44  Female          0
4   55    Male          2
5   22    Male          2
6   35   LGBTQ          1

In [98]:
df["gender_tf"].unique()

array([2, 0, 1])

In [99]:
df.head(11)

   Age  Gender  gender_tf
0   33    Male          2
1   44  Female          0
2   22    Male          2
3   44  Female          0
4   55    Male          2
5   22    Male          2
6   35   LGBTQ          1

In [100]:
import pandas as pd
df = pd.DataFrame([('Sholay', 289.0),
                   ('KGf', 224.0),
                   ('RRR', 80.5),
                   ('Sholay', 25.30)],
           columns=('Cinema_name', 'Amount')
                 )
df.head()

  Cinema_name  Amount
0      Sholay   289.0
1         KGf   224.0
2         RRR    80.5
3      Sholay    25.3

In [101]:
df["Cinema_name"].value_counts()

Cinema_name
Sholay    2
KGf       1
RRR       1
Name: count, dtype: int64

In [102]:
pd.get_dummies(df, columns=['Cinema_name'],dtype=int)

   Amount  Cinema_name_KGf  Cinema_name_RRR  Cinema_name_Sholay
0   289.0                0                0                   1
1   224.0                1                0                   0
2    80.5                0                1                   0
3    25.3                0                0                   1

In [103]:
pd.get_dummies(df, columns=['Cinema_name'],dtype=int, prefix="enc",prefix_sep="##__")

   Amount  enc##__KGf  enc##__RRR  enc##__Sholay
0   289.0           0           0              1
1   224.0           1           0              0
2    80.5           0           1              0
3    25.3           0           0              1

In [104]:
pd.get_dummies(df, columns=['Cinema_name'],drop_first=True)

   Amount  Cinema_name_RRR  Cinema_name_Sholay
0   289.0            False                True
1   224.0            False               False
2    80.5             True               False
3    25.3            False                True

In [105]:
# ...The End