# Pandas - paneled datas
    pandas are very famous python library for handling the datas
    => reading the different types of files and get the data into python data frame
    => creating the different types of files from python data frame such as (csv, excel, json, parquet, ...etc)
    => creating series, dataframes to handle the file datas
    => handling the noisy datas such as null datas, duplicates data's, wrong format datas
    => comparison, creating new columns, getting info about the data, modify the existing data, central tendency finding, row based filter, column based filter, joining one csv dataframe to another csv dataframes (inner, left, right, outer)

In [ ]:
!pip install pandas

In [9]:
import pandas as pd
print(pd.__version__)

2.3.0

In [10]:
import pandas as pd
print(pd.__doc__)

pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [11]:
# pandas series are one dimensional arrays which have only one column with index position as row names
import pandas as pd

l1 = [5,2,9,3,1]

s1 = pd.Series(l1)# the index column of a series will 0, 1,
s1

0    5
1    2
2    9
3    3
4    1
dtype: int64

In [12]:
s1.shape # 1 column(for a series always column will be one so it won't return) 5 rows

(5,)

In [13]:
s1.min()

1

In [14]:
s1.sum()

20

In [15]:
s1[2]

9

In [16]:
# converting 2D arry in a series

import pandas as pd
import numpy as np


arr = np.random.randint(3,15,(4,3))
print(arr)

# 2D arrays cannot be converted as series
s1 = pd.Series(arr)
s1

[[ 7 10  8]
 [12  4  3]
 [14 11  9]
 [11 10  8]]

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 3) instead

In [17]:
d1 = {"apple":34, "orange":45, "banana":12}

# when we convert a dictionary as a series the keys will appear as row name

s2 = pd.Series(d1)
s2

apple     34
orange    45
banana    12
dtype: int64

In [18]:
l1 = [5,2,9,3,1]

s1 = pd.Series(l1, index = ("a","b", "c","d", "e")) # changing the labels of the rows
s1

a    5
b    2
c    9
d    3
e    1
dtype: int64

In [19]:
s1["c"]

9

In [20]:
s1["a", "c", "e"]

KeyError: 'key of type tuple not found and not a MultiIndex'

In [21]:
l1 = [5,2,9,"hello",1, 4.5]

s1 = pd.Series(l1, index = ("a","b", "c","d", "e", "f")) # changing the labels of the rows
s1

a        5
b        2
c        9
d    hello
e        1
f      4.5
dtype: object

In [23]:
# dataframes -- are rows and columns table format 
# dataframes -- twodimensional, size mutable, hetrogeneous tabular datastructure
import pandas as pd
d2 = {
    "Jobs" : ["backend developer", "AI engineer", "data analyst"],
    "City" : ["Ney York", "San francisco", "washington dc"],
    "Salary" : [40000,50000,30000]
}

df = pd.DataFrame(d2)
df

                Jobs           City  Salary
0  backend developer       Ney York   40000
1        AI engineer  San francisco   50000
2       data analyst  washington dc   30000

In [24]:
df.loc[1] # fetching row name based data fetch

Jobs        AI engineer
City      San francisco
Salary            50000
Name: 1, dtype: object

In [25]:
df.iloc[2] #this works based on index

Jobs       data analyst
City      washington dc
Salary            30000
Name: 2, dtype: object

In [16]:
# slicing the rows
df.loc[:1]

                Jobs           City  Salary
0  backend developer       Ney York   40000
1        AI engineer  San francisco   50000

In [26]:
df.loc[:1]["Jobs"]

0    backend developer
1          AI engineer
Name: Jobs, dtype: object

In [27]:
print(df)
df.loc[1][2] # fetching the "specific data from the dataframe

                Jobs           City  Salary
0  backend developer       Ney York   40000
1        AI engineer  San francisco   50000
2       data analyst  washington dc   30000

C:\Users\pugal\AppData\Local\Temp\ipykernel_30032\296397639.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[1][2] # fetching the "specific data from the dataframe

50000

In [28]:
df["City"]  # fethcing the column

0         Ney York
1    San francisco
2    washington dc
Name: City, dtype: object

In [19]:
df["City"][2] # retriving the specific data from coloumn

'washington dc'

In [29]:
d2 = {
    "Jobs" : ["backend developer", "AI engineer", "data analyst"],
    "City" : ["Ney York", "San francisco", "washington dc"],
    "Salary" : [40000,50000,30000]
}

df = pd.DataFrame(d2, index = ("record1", "record2", "record3")) # instead of going with default index
                                                                # we define out own index for df
df

                      Jobs           City  Salary
record1  backend developer       Ney York   40000
record2        AI engineer  San francisco   50000
record3       data analyst  washington dc   30000

In [30]:
# fetching the record based on index name
df.loc["record2"]

Jobs        AI engineer
City      San francisco
Salary            50000
Name: record2, dtype: object

In [31]:
df.loc[1]

KeyError: 1

In [32]:
df.iloc[2] # retriving the data based on index count

Jobs       data analyst
City      washington dc
Salary            30000
Name: record3, dtype: object

In [33]:
df.iloc["record1"]

TypeError: Cannot index by location index with a non-integer key

In [35]:
# reading the files using pandas
import pandas as pd
#csv file

df = pd.read_csv("employee.csv")
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [36]:
# reading the json file
df = pd.read_json("employee.json")
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4    None  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0      None   37  Female

In [44]:
# to enable python to read any excel file we use xlrd -library
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\pugal\appdata\local\programs\python\python311\lib\site-packages (2.0.1)

WARNING: Error parsing dependencies of textract: .* suffix can only be used with `==` or `!=` operators
    extract-msg (<=0.29.*)
                 ~~~~~~~^

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
# reading the excel file
import pandas as pd
df = pd.read_excel("file_example_XLS_50.xlsx")
df

     0 First Name   Last Name  Gender        Country  Age        Date    Id
0    1      Dulce       Abril  Female  United States   32  15/10/2017  1562
1    2       Mara   Hashimoto  Female  Great Britain   25  16/08/2016  1582
2    3     Philip        Gent    Male         France   36  21/05/2015  2587
3    4   Kathleen      Hanner  Female  United States   25  15/10/2017  3549
4    5    Nereida     Magwood  Female  United States   58  16/08/2016  2468
5    6     Gaston       Brumm    Male  United States   24  21/05/2015  2554
6    7       Etta        Hurn  Female  Great Britain   56  15/10/2017  3598
7    8    Earlean      Melgar  Female  United States   27  16/08/2016  2456
8    9   Vincenza     Weiland  Female  United States   40  21/05/2015  6548
9   10     Fallon     Winward  Female  Great Britain   28  16/08/2016  5486
10  11    Arcelia      Bouska  Female  Great Britain   39  21/05/2015  1258
11  12   Franklyn      Unknow    Male         France   38  15/10/2017  2579
12  13    Sherron    Ascencio  Female  Great Britain   32  16/08/2016  3256
13  14     Marcel   Zabriskie    Male  Great Britain   26  21/05/2015  2587
14  15       Kina    Hazelton  Female  Great Britain   31  16/08/2016  3259
15  16   Shavonne         Pia  Female         France   24  21/05/2015  1546
16  17     Shavon      Benito  Female         France   39  15/10/2017  3579
17  18   Lauralee     Perrine  Female  Great Britain   28  16/08/2016  6597
18  19     Loreta      Curren  Female         France   26  21/05/2015  9654
19  20     Teresa      Strawn  Female         France   46  21/05/2015  3569
20  21    Belinda     Partain  Female  United States   37  15/10/2017  2564
21  22      Holly        Eudy  Female  United States   52  16/08/2016  8561
22  23       Many      Cuccia  Female  Great Britain   46  21/05/2015  5489
23  24     Libbie       Dalby  Female         France   42  21/05/2015  5489
24  25     Lester     Prothro    Male         France   21  15/10/2017  6574
25  26     Marvel        Hail  Female  Great Britain   28  16/08/2016  5555
26  27    Angelyn        Vong  Female  United States   29  21/05/2015  6125
27  28  Francesca   Beaudreau  Female         France   23  15/10/2017  5412
28  29      Garth       Gangi    Male  United States   41  16/08/2016  3256
29  30      Carla    Trumbull  Female  Great Britain   28  21/05/2015  3264
30  31       Veta       Muntz  Female  Great Britain   37  15/10/2017  4569
31  32     Stasia      Becker  Female  Great Britain   34  16/08/2016  7521
32  33       Jona     Grindle  Female  Great Britain   26  21/05/2015  6458
33  34      Judie    Claywell  Female         France   35  16/08/2016  7569
34  35     Dewitt      Borger    Male  United States   36  21/05/2015  8514
35  36       Nena      Hacker  Female  United States   29  15/10/2017  8563
36  37     Kelsie     Wachtel  Female         France   27  16/08/2016  8642
37  38        Sau        Pfau  Female  United States   25  21/05/2015  9536
38  39    Shanice   Mccrystal  Female  United States   36  21/05/2015  2567
39  40      Chase      Karner    Male  United States   37  15/10/2017  2154
40  41     Tommie   Underdahl    Male  United States   26  16/08/2016  3265
41  42     Dorcas      Darity  Female  United States   37  21/05/2015  8765
42  43      Angel       Sanor    Male         France   24  15/10/2017  3259
43  44  Willodean        Harn  Female  United States   39  16/08/2016  3567
44  45     Weston     Martina    Male  United States   26  21/05/2015  6540
45  46       Roma  Lafollette  Female  United States   34  15/10/2017  2654
46  47     Felisa        Cail  Female  United States   28  16/08/2016  6525
47  48   Demetria       Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy        Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda      Alkire  Female  United States   29  16/08/2016  6125

In [2]:
df.head()  # head() without args will return first 5 records of the dataframe

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [3]:
df.head(8) # fetch first specific number of records

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456

In [4]:
df.tail(3) # returns last 3 records from the df

     0 First Name Last Name  Gender        Country  Age        Date    Id
47  48   Demetria     Abbey  Female  United States   32  21/05/2015  3265
48  49     Jeromy      Danz    Male  United States   39  15/10/2017  3265
49  50   Rasheeda    Alkire  Female  United States   29  16/08/2016  6125

In [5]:
df.shape

(50, 8)

In [6]:
df.columns

Index([0, 'First Name', 'Last Name', 'Gender', 'Country', 'Age', 'Date', 'Id'], dtype='object')

In [43]:
# retriving unique values from the specific column
df["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [9]:
# handling the datas in a dataframe
import pandas as pd
df = pd.read_csv("employee.csv")
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [10]:
# to remove the null record rows we use dropna() -- immutable

df1 = df.dropna() 
df1

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
5    john  3000.0  4.0  losvegas   33  Female
8     doe  4000.0  5.0        dc   25  Female

In [11]:
df = pd.read_csv("employee.csv")
df.dropna(inplace = True)  # changing the current dataframe itself  -- mutable
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
5    john  3000.0  4.0  losvegas   33  Female
8     doe  4000.0  5.0        dc   25  Female

In [12]:
# using fillna("replace value")  replacing the null records from all over the dataframe

df = pd.read_csv("employee.csv")
df.fillna("python",inplace = True)
df

C:\Users\pugal\AppData\Local\Temp\ipykernel_21940\1831355485.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'python' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("python",inplace = True)

     name  salary     exp      city  age  Gender
0    john  3000.0     4.0  losvegas   30    Male
1     doe  4000.0     5.0        dc   25  Female
2  robert  8000.0     6.0     paris   27    Male
3   chris  9000.0     7.0   newyork   24  Female
4  python  3000.0  python  losvegas   35    Male
5    john  3000.0     4.0  losvegas   33  Female
6   evans  python     4.0  losvegas   31    Male
7     tom  3000.0     4.0    python   37  Female
8     doe  4000.0     5.0        dc   25  Female

In [13]:
# replace the null values on specific cols

df = pd.read_csv("employee.csv")
df["name"].fillna("python",inplace = True)
df

C:\Users\pugal\AppData\Local\Temp\ipykernel_21940\2808676864.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("python",inplace = True)

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4  python  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [14]:
df = pd.read_csv("employee.csv")
# removes the rows that contains null value on the exp column
df.dropna(subset = "exp", inplace = True)
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [43]:
import pandas as pd
df = pd.read_csv("employee.csv")
print(df)
df.drop_duplicates(inplace=True)
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female

In [1]:
import pandas as pd
df = pd.read_csv("employee.csv")
df.info() # will return the number of rows and cols and types of the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      object
 1   salary  8 non-null      float64
 2   exp     8 non-null      float64
 3   city    8 non-null      object
 4   age     9 non-null      int64
 5   Gender  9 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 564.0+ bytes

In [14]:
df = pd.read_csv("employee.csv")

df.describe()  # will return the central tendency of your dataframe will work on integers cols only

            salary       exp        age
count     8.000000  8.000000   9.000000
mean   4625.000000  4.875000  29.666667
std    2445.841953  1.125992   4.716991
min    3000.000000  4.000000  24.000000
25%    3000.000000  4.000000  25.000000
50%    3500.000000  4.500000  30.000000
75%    5000.000000  5.250000  33.000000
max    9000.000000  7.000000  37.000000

In [2]:
# replacing the mean value for null

df = pd.read_csv("employee.csv")

df["salary"].fillna(df["salary"].mean(), inplace = True)#median(), mode()
df

C:\Users\pugal\AppData\Local\Temp\ipykernel_24092\2232268100.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["salary"].fillna(df["salary"].mean(), inplace = True)#median(), mode()

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans  4625.0  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [15]:
# replacing the mean value for null

df = pd.read_csv("employee.csv")
median_value = df["exp"].median()

df["exp"].fillna(median_value, inplace = True)#median(), mode()
df

C:\Users\pugal\AppData\Local\Temp\ipykernel_21940\3483658028.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["exp"].fillna(median_value, inplace = True)#median(), mode()

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  4.5  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [18]:
df = pd.read_csv("employee.csv")

print(df["salary"]>4000)  # boolean masking

0    False
1    False
2     True
3     True
4    False
5    False
6    False
7    False
8    False
Name: salary, dtype: bool

In [16]:

df = pd.read_csv("employee.csv")

print(df[df["salary"]>4000])  # applying the boolean masking

     name  salary  exp     city  age  Gender
2  robert  8000.0  6.0    paris   27    Male
3   chris  9000.0  7.0  newyork   24  Female

In [17]:
df["hike"] = df["salary"]+2000  # creating a new col
df

     name  salary  exp      city  age  Gender     hike
0    john  3000.0  4.0  losvegas   30    Male   5000.0
1     doe  4000.0  5.0        dc   25  Female   6000.0
2  robert  8000.0  6.0     paris   27    Male  10000.0
3   chris  9000.0  7.0   newyork   24  Female  11000.0
4     NaN  3000.0  NaN  losvegas   35    Male   5000.0
5    john  3000.0  4.0  losvegas   33  Female   5000.0
6   evans     NaN  4.0  losvegas   31    Male      NaN
7     tom  3000.0  4.0       NaN   37  Female   5000.0
8     doe  4000.0  5.0        dc   25  Female   6000.0

In [18]:
df.drop(columns= "hike", inplace=True)
#df.drop(columns= ["hike","age"], inplace=True) -- dropping multiple cols
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [19]:
df = pd.read_csv("employee.csv")

print(df[(df["salary"]>4000) & (df["exp"]<7)])  # multiple conditions

     name  salary  exp    city  age Gender
2  robert  8000.0  6.0   paris   27   Male

In [20]:
df = pd.read_csv("employee.csv")

print(df[(df["salary"]>4000) | (df["exp"]<7)])  # multiple conditions

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [22]:
df[~(df["Gender"] == "Male")]

    name  salary  exp      city  age  Gender
1    doe  4000.0  5.0        dc   25  Female
3  chris  9000.0  7.0   newyork   24  Female
5   john  3000.0  4.0  losvegas   33  Female
7    tom  3000.0  4.0       NaN   37  Female
8    doe  4000.0  5.0        dc   25  Female

In [23]:
df = pd.read_csv("employee.csv")

df.loc[:4] # multiple conditions    # Access first row by label

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male

In [24]:
df = pd.read_csv("employee.csv")

df.loc[:4, ("name", "city")]

     name      city
0    john  losvegas
1     doe        dc
2  robert     paris
3   chris   newyork
4     NaN  losvegas

In [25]:
import pandas as pd
df = pd.read_csv("employee.csv")

df.loc[:2, "city"] = "unnamed city"
df

     name  salary  exp          city  age  Gender
0    john  3000.0  4.0  unnamed city   30    Male
1     doe  4000.0  5.0  unnamed city   25  Female
2  robert  8000.0  6.0  unnamed city   27    Male
3   chris  9000.0  7.0       newyork   24  Female
4     NaN  3000.0  NaN      losvegas   35    Male
5    john  3000.0  4.0      losvegas   33  Female
6   evans     NaN  4.0      losvegas   31    Male
7     tom  3000.0  4.0           NaN   37  Female
8     doe  4000.0  5.0            dc   25  Female

In [26]:
df[["name", "exp"]]

     name  exp
0    john  4.0
1     doe  5.0
2  robert  6.0
3   chris  7.0
4     NaN  NaN
5    john  4.0
6   evans  4.0
7     tom  4.0
8     doe  5.0

In [27]:
df["name"]

0      john
1       doe
2    robert
3     chris
4       NaN
5      john
6     evans
7       tom
8       doe
Name: name, dtype: object

In [28]:
def percent(val):
    result = (val/10000)*100
    return result


df = pd.read_csv("employee.csv")

#df["percent"] = df["salary"].apply(percent)
df["percent"] = df["salary"].apply(percent)
df

     name  salary  exp      city  age  Gender  percent
0    john  3000.0  4.0  losvegas   30    Male     30.0
1     doe  4000.0  5.0        dc   25  Female     40.0
2  robert  8000.0  6.0     paris   27    Male     80.0
3   chris  9000.0  7.0   newyork   24  Female     90.0
4     NaN  3000.0  NaN  losvegas   35    Male     30.0
5    john  3000.0  4.0  losvegas   33  Female     30.0
6   evans     NaN  4.0  losvegas   31    Male      NaN
7     tom  3000.0  4.0       NaN   37  Female     30.0
8     doe  4000.0  5.0        dc   25  Female     40.0

In [20]:
df = pd.read_csv("employee.csv")

df[~(df["salary"]<5000)]  # negate operator

     name  salary  exp      city  age  Gender
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
6   evans     NaN  4.0  losvegas   31    Male

In [29]:
import pandas as pd
# !pip install mysql-connector-python
from mysql import connector
connection = connector.connect(user = "root", password = "12345", host = "localhost", db = "emp")
df = pd.read_sql('SELECT * FROM empcopy', connection)
df

C:\Users\pugal\AppData\Local\Temp\ipykernel_21940\1599447490.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('SELECT * FROM empcopy', connection)

,job,dept,city,sal,address,incentive
0,front end,javascript developer,washingto dc,35000.0,"sanfrancisco, us",NaN
1,backend end,IT,bleeker street dc,40000.0,"los vegas, us",NaN
2,AI,IT,manhatton dc,50000.0,"los angeles, us",1600.0
3,ML developer,IT,san francisco,11000.0,str1 manhattan,NaN
4,data analyst,IT,los angeles,70000.0,str1 manhattan,NaN
...,...,...,...,...,...,...
58,driver,racing,malibu,85000.0,"WTC angeles tower, canada",470.0
59,tourist guide,guiding,malibu,85000.0,"pais angeles tower, canada",470.0
60,weather anlyst,analysis,banglore,63000.0,"whitfield, winter,banglore town",900.0
61,Inspector detective,crime resolver,police st,89000.0,"cop angeles quarters, station",470.0
62,User interface developer,None,banglore,45000.0,whitefield,1000.0

In [30]:
df = pd.read_csv("employee.csv")
#df.mean()  # only if the each col is numeric it will work

In [31]:
df[["exp", "salary"]].mean()

exp          4.875
salary    4625.000
dtype: float64

In [32]:
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [33]:
df.groupby('city').sum()  # Group data by column 'A' and sum

                   name  salary   exp  age              Gender
city
 dc              doedoe  8000.0  10.0   50        FemaleFemale
 paris           robert  8000.0   6.0   27                Male
losvegas  johnjohnevans  9000.0  12.0  129  MaleMaleFemaleMale
newyork           chris  9000.0   7.0   24              Female

In [11]:
df.groupby('city').sum()  # Group data by column 'A' and sum

                   name  salary   exp  age              Gender
city
 dc              doedoe  8000.0  10.0   50        FemaleFemale
 paris           robert  8000.0   6.0   27                Male
losvegas  johnjohnevans  9000.0  12.0  129  MaleMaleFemaleMale
newyork           chris  9000.0   7.0   24              Female

In [34]:
#df.groupby('city').sum(["exp"])  # Group data by column 'A' and sum
df.groupby('city')['salary'].sum()

city
 dc         8000.0
 paris      8000.0
losvegas    9000.0
newyork     9000.0
Name: salary, dtype: float64

In [406]:
import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, 3]})
df2 = pd.DataFrame({'B': [4, 5, 6]})
print(df1)
print(df2)
result = pd.concat([df1, df2], axis=1)  # adding columns parallely
result

   A
0  1
1  2
2  3
   B
0  4
1  5
2  6

   A  B
0  1  4
1  2  5
2  3  6

In [14]:
df1 = pd.DataFrame({'A': [1, 2, 3]})
df2 = pd.DataFrame({'B': [4, 5, 6]})
print(df1)
print(df2)
result = pd.concat([df1, df2], axis=0)  #  adding df vertically

result

   A
0  1
1  2
2  3
   B
0  4
1  5
2  6

     A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
0  NaN  4.0
1  NaN  5.0
2  NaN  6.0

In [35]:
import pandas as pd
left = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
right = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
print(left)
print(right)
merged = pd.merge(left, right, on='key', how='inner')
merged

  key  value
0   A      1
1   B      2
2   C      3
  key  value
0   A      4
1   B      5
2   D      6

  key  value_x  value_y
0   A        1        4
1   B        2        5

In [1]:
import pandas as pd

left = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
right = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
print(left)
print(right)
merged = pd.merge(left, right, on='key', how='outer')
merged

  key  value
0   A      1
1   B      2
2   C      3
  key  value
0   A      4
1   B      5
2   D      6

  key  value_x  value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [17]:
left = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
right = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
print(left)
print(right)
merged = pd.merge(left, right, on='key', how='left')
merged

  key  value
0   A      1
1   B      2
2   C      3
  key  value
0   A      4
1   B      5
2   D      6

  key  value_x  value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [2]:
left = pd.DataFrame({'key': ['A', 'B', 'C'], 'value': [1, 2, 3]})
right = pd.DataFrame({'key': ['A', 'B', 'D'], 'value': [4, 5, 6]})
print(left)
print(right)
merged = pd.merge(left, right, on='key', how='right')
#merged = pd.merge(left, right, on='key') default inner
merged

  key  value
0   A      1
1   B      2
2   C      3
  key  value
0   A      4
1   B      5
2   D      6

  key  value_x  value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6

In [6]:
df = pd.read_csv('employee.csv')
df["Date"] = "2024/08/12"
df

     name  salary  exp      city  age  Gender        Date
0    john  3000.0  4.0  losvegas   30    Male  2024/08/12
1     doe  4000.0  5.0        dc   25  Female  2024/08/12
2  robert  8000.0  6.0     paris   27    Male  2024/08/12
3   chris  9000.0  7.0   newyork   24  Female  2024/08/12
4     NaN  3000.0  NaN  losvegas   35    Male  2024/08/12
5    john  3000.0  4.0  losvegas   33  Female  2024/08/12
6   evans     NaN  4.0  losvegas   31    Male  2024/08/12
7     tom  3000.0  4.0       NaN   37  Female  2024/08/12
8     doe  4000.0  5.0        dc   25  Female  2024/08/12

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

df

     name  salary  exp      city  age  Gender       Date
0    john  3000.0  4.0  losvegas   30    Male 2024-08-12
1     doe  4000.0  5.0        dc   25  Female 2024-08-12
2  robert  8000.0  6.0     paris   27    Male 2024-08-12
3   chris  9000.0  7.0   newyork   24  Female 2024-08-12
4     NaN  3000.0  NaN  losvegas   35    Male 2024-08-12
5    john  3000.0  4.0  losvegas   33  Female 2024-08-12
6   evans     NaN  4.0  losvegas   31    Male 2024-08-12
7     tom  3000.0  4.0       NaN   37  Female 2024-08-12
8     doe  4000.0  5.0        dc   25  Female 2024-08-12

In [8]:
df["Date+1"] = df['Date'] + pd.Timedelta(days=5)  # Add 1 day to each date
df

     name  salary  exp      city  age  Gender       Date     Date+1
0    john  3000.0  4.0  losvegas   30    Male 2024-08-12 2024-08-17
1     doe  4000.0  5.0        dc   25  Female 2024-08-12 2024-08-17
2  robert  8000.0  6.0     paris   27    Male 2024-08-12 2024-08-17
3   chris  9000.0  7.0   newyork   24  Female 2024-08-12 2024-08-17
4     NaN  3000.0  NaN  losvegas   35    Male 2024-08-12 2024-08-17
5    john  3000.0  4.0  losvegas   33  Female 2024-08-12 2024-08-17
6   evans     NaN  4.0  losvegas   31    Male 2024-08-12 2024-08-17
7     tom  3000.0  4.0       NaN   37  Female 2024-08-12 2024-08-17
8     doe  4000.0  5.0        dc   25  Female 2024-08-12 2024-08-17

In [4]:
df = pd.read_csv("employee.csv")
df[["exp", "salary"]].corr() ## Compute pairwise correlation of columns

             exp    salary
exp     1.000000  0.964203
salary  0.964203  1.000000

In [5]:
df

     name  salary  exp      city  age  Gender
0    john  3000.0  4.0  losvegas   30    Male
1     doe  4000.0  5.0        dc   25  Female
2  robert  8000.0  6.0     paris   27    Male
3   chris  9000.0  7.0   newyork   24  Female
4     NaN  3000.0  NaN  losvegas   35    Male
5    john  3000.0  4.0  losvegas   33  Female
6   evans     NaN  4.0  losvegas   31    Male
7     tom  3000.0  4.0       NaN   37  Female
8     doe  4000.0  5.0        dc   25  Female

In [6]:
#df.pivot_table(values='value', index='category', columns='date', aggfunc='sum')
df.set_index('name', inplace=True)  # Set column A as the index
df

        salary  exp      city  age  Gender
name
john    3000.0  4.0  losvegas   30    Male
doe     4000.0  5.0        dc   25  Female
robert  8000.0  6.0     paris   27    Male
chris   9000.0  7.0   newyork   24  Female
NaN     3000.0  NaN  losvegas   35    Male
john    3000.0  4.0  losvegas   33  Female
evans      NaN  4.0  losvegas   31    Male
tom     3000.0  4.0       NaN   37  Female
doe     4000.0  5.0        dc   25  Female

In [7]:
import pandas as pd
df = pd.read_csv("employee.csv")
df = df.set_index(['name', 'city'])  # Set multiple columns as index
df

                 salary  exp  age  Gender
name   city
john   losvegas  3000.0  4.0   30    Male
doe     dc       4000.0  5.0   25  Female
robert  paris    8000.0  6.0   27    Male
chris  newyork   9000.0  7.0   24  Female
NaN    losvegas  3000.0  NaN   35    Male
john   losvegas  3000.0  4.0   33  Female
evans  losvegas     NaN  4.0   31    Male
tom    NaN       3000.0  4.0   37  Female
doe     dc       4000.0  5.0   25  Female

In [8]:
df.reset_index(inplace=True)  # Reset index to default integer index
df

     name      city  salary  exp  age  Gender
0    john  losvegas  3000.0  4.0   30    Male
1     doe        dc  4000.0  5.0   25  Female
2  robert     paris  8000.0  6.0   27    Male
3   chris   newyork  9000.0  7.0   24  Female
4     NaN  losvegas  3000.0  NaN   35    Male
5    john  losvegas  3000.0  4.0   33  Female
6   evans  losvegas     NaN  4.0   31    Male
7     tom       NaN  3000.0  4.0   37  Female
8     doe        dc  4000.0  5.0   25  Female

In [9]:
df.query('exp > 1 & salary < 5000')  # Similar to SQL-like queries

   name      city  salary  exp  age  Gender
0  john  losvegas  3000.0  4.0   30    Male
1   doe        dc  4000.0  5.0   25  Female
5  john  losvegas  3000.0  4.0   33  Female
7   tom       NaN  3000.0  4.0   37  Female
8   doe        dc  4000.0  5.0   25  Female

In [10]:

df = pd.read_csv("employee.csv")
df = df.dropna() # cannot do the following operations with nan values
df[df['name'].str.contains('jo')]  # Filter rows where column 'A' contains 'abc'

   name  salary  exp      city  age  Gender
0  john  3000.0  4.0  losvegas   30    Male
5  john  3000.0  4.0  losvegas   33  Female

In [25]:
df.groupby(['name', 'city']).sum()  # Group by columns A and B, and sum other columns

                 salary   exp  age        Gender
name   city
chris  newyork   9000.0   7.0   24        Female
doe     dc       8000.0  10.0   50  FemaleFemale
evans  losvegas     0.0   4.0   31          Male
john   losvegas  6000.0   8.0   63    MaleFemale
robert  paris    8000.0   6.0   27          Male

In [16]:
import pandas as pd

# Input DataFrame
data = {
    "city": [
        "Jacksonville", "Jacksonville", "Jacksonville", "Jacksonville", "Jacksonville",
        "ElPaso", "ElPaso", "ElPaso", "ElPaso", "ElPaso"
    ],
    "month": ["January", "February", "March", "April", "May", 
              "January", "February", "March", "April", "May"],
    "temperature": [13, 23, 38, 5, 34, 20, 6, 26, 2, 43]
}

df = pd.DataFrame(data)

#print(df)
# Pivot the data
pivoted_df = df.pivot(index="month", columns="city", values="temperature")

# Reset the index if needed and sort the rows by month
#pivoted_df = pivoted_df.reset_index().sort_values(by="month")

# Display the result
pivoted_df

city      ElPaso  Jacksonville
month
April          2             5
February       6            23
January       20            13
March         26            38
May           43            34

In [2]:
! pip install requests

Requirement already satisfied: requests in c:\users\pugal\appdata\local\programs\python\python311\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pugal\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pugal\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pugal\appdata\local\programs\python\python311\lib\site-packages (from requests) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pugal\appdata\local\programs\python\python311\lib\site-packages (from requests) (2024.12.14)

WARNING: Error parsing dependencies of textract: .* suffix can only be used with `==` or `!=` operators
    extract-msg (<=0.29.*)
                 ~~~~~~~^

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import requests

# GET request Basic Usage
response = requests.get("https://jsonplaceholder.typicode.com/posts/1")

print(response.status_code)   # HTTP status code (200 = OK)
print(response.text)          # Response as raw text
print(response.json())        # If response is JSON, convert to Python dict

200
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [3]:
# Sending Parameters

params = {"userId": 1} # userid -1 has 10 records
response = requests.get("https://jsonplaceholder.typicode.com/posts", params=params)
print(response.json())

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic commodi nesciunt rem tenetur doloremque ipsam iure\nquis sunt voluptatem rerum illo velit'}, {'userId': 1, 'id': 5, 'title': 'nesciunt quas odio', 'body': 'repudiandae veniam quaerat sunt sed\nalias aut fugiat sit autem sed est\nvoluptatem omnis possimus esse voluptatibus quis\nest aut tenetur dolor neque'}, {'userId': 1, 'id': 6, 'title': 'dolorem eum magni eos aperiam quia', 'body': 'ut aspernatur corporis harum nihil quis provident sequi\nmollitia nobis aliquid molestiae\nperspiciatis et ea nemo ab reprehenderit accusantium quas\nvoluptate dolores velit et doloremque molestiae'}, {'userId': 1, 'id': 7, 'title': 'magnam facilis autem', 'body': 'dolore placeat quibusdam ea quo vitae\nmagni quis enim qui quis quo nemo aut saepe\nquidem repellat excepturi ut quia\nsunt ut sequi eos ea sed quas'}, {'userId': 1, 'id': 8, 'title': 'dolorem dolore est ipsam', 'body': 'dignissimos aperiam dolorem qui eum\nfacilis quibusdam animi sint suscipit qui sint possimus cum\nquaerat magni maiores excepturi\nipsam ut commodi dolor voluptatum modi aut vitae'}, {'userId': 1, 'id': 9, 'title': 'nesciunt iure omnis dolorem tempora et accusantium', 'body': 'consectetur animi nesciunt iure dolore\nenim quia ad\nveniam autem ut quam aut nobis\net est aut quod aut provident voluptas autem voluptas'}, {'userId': 1, 'id': 10, 'title': 'optio molestias id quia eum', 'body': 'quo et expedita modi cum officia vel magni\ndoloribus qui repudiandae\nvero nisi sit\nquos veniam quod sed accusamus veritatis error'}]

In [4]:
#POST request
data = {"title": "Hello", "body": "World", "userId": 1}
response = requests.post("https://jsonplaceholder.typicode.com/posts", json=data)
print(response.status_code)
print(response.json())

201
{'title': 'Hello', 'body': 'World', 'userId': 1, 'id': 101}

In [7]:
# Adding Headers
headers = {"Authorization": "Bearer my_token"}
response = requests.get("https://jsonplaceholder.typicode.com/posts", headers=headers)
print(response.status_code)

200

In [8]:
# Handling Errors

try:
    response = requests.get("https://api.example.com/404")
    response.raise_for_status()  # raises exception for 4xx/5xx
except requests.exceptions.RequestException as e:
    print("Error:", e)

Error: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /404 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017824487650>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))

In [10]:
data = {"title": "New Post", "body": "Hello World", "userId": 1}
response = requests.post("https://jsonplaceholder.typicode.com/posts", json=data)
print(response.status_code)
print(response.json())   # shows new post with ID

201
{'title': 'New Post', 'body': 'Hello World', 'userId': 1, 'id': 101}

In [11]:
data = {"id": 1, "title": "Updated Title", "body": "Updated Body", "userId": 1}
response = requests.put("https://jsonplaceholder.typicode.com/posts/1", json=data)
print(response.status_code)
print(response.json())

200
{'id': 1, 'title': 'Updated Title', 'body': 'Updated Body', 'userId': 1}

In [12]:
response = requests.delete("https://jsonplaceholder.typicode.com/posts/1")
print(response.status_code)   # 200 = success, 204 = no content

200

In [13]:
response = requests.head("https://jsonplaceholder.typicode.com/posts/1")
print(response.headers)

{'Date': 'Thu, 30 Oct 2025 02:15:59 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'Cache-Control': 'max-age=43200', 'etag': 'W/"124-yiKdLzqO5gfBrJFrcdJ8Yq0LGnU"', 'expires': '-1', 'nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'pragma': 'no-cache', 'report-to': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=8p0NeBqkU1l3cNHGU9MTdKLAttflEtcqx1ssyzWX5SI%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1761763697"}],"max_age":3600}', 'reporting-endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=8p0NeBqkU1l3cNHGU9MTdKLAttflEtcqx1ssyzWX5SI%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1761763697"', 'Server': 'cloudflare', 'vary': 'Origin, Accept-Encoding', 'via': '2.0 heroku-router', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'x-ratelimit-limit': '1000', 'x-ratelimit-remaining': '999', 'x-ratelimit-reset': '1761763750', 'Age': '26862', 'cf-cache-status': 'HIT', 'Content-Encoding': 'gzip', 'CF-RAY': '996768773f543c06-BLR', 'alt-svc': 'h3=":443"; ma=86400'}